CREATE TABLE IF NOT EXISTS "elevenlabs-hack_journal_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "elevenlabs-hack_journal_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"raw_entry" text NOT NULL,
	"summarized_entry" text NOT NULL,
	"mood_score" numeric(5, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "elevenlabs-hack_journal_entry" USING btree ("created_at");